# Generated by Django 5.1.4 on 2026-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('nda_created', 'NDA Created'), ('nda_updated', 'NDA Updated'), ('nda_version_created', 'Version Created'), ('nda_activated', 'NDA Activated'), ('nda_archived', 'NDA Archived'), ('nda_deleted', 'NDA Deleted'), ('person_created', 'Person Created'), ('person_updated', 'Person Updated'), ('nda_assigned', 'NDA Assigned'), ('nda_group_assigned', 'Group Assigned'), ('nda_signed', 'NDA Signed'), ('nda_declined', 'NDA Declined'), ('nda_revoked', 'NDA Revoked'), ('nda_reminded', 'Reminder Sent'), ('doc_downloaded', 'Document Downloaded')], db_index=True, max_length=30),
        ),
    ]
