# Generated by Django 5.1.4 on 2026-02-19 09:05

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signer_company', models.CharField(blank=True, default='', max_length=255)),
                ('signer_designation', models.CharField(blank=True, default='', max_length=255)),
                ('signer_person_type', models.CharField(max_length=20)),
                ('nda_name', models.CharField(max_length=255)),
                ('nda_category', models.CharField(max_length=20)),
                ('nda_version', models.CharField(max_length=20)),
                ('nda_content_html', models.TextField()),
                ('nda_content_plain', models.TextField()),
                ('nda_content_hash', models.CharField(max_length=128)),
                ('nda_copy_docx', models.FileField(blank=True, null=True, upload_to=documents.models._copy_path)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=documents.models._sig_path)),
                ('signature_type', models.CharField(default='drawn', max_length=20)),
                ('signature_hash', models.CharField(blank=True, default='', max_length=128)),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to=documents.models._signed_path)),
                ('consent_text', models.TextField()),
                ('consent_given', models.BooleanField(default=True)),
                ('consent_timestamp', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signed_document', to='assignments.ndaassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
