# Generated by Django 5.1.4 on 2026-02-19 09:05

import assignments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ndas', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NDAAssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('link_expiry_hours', models.IntegerField(default=72)),
                ('total_assignments', models.IntegerField(default=0)),
                ('total_signed', models.IntegerField(default=0)),
                ('total_pending', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nda_templates', models.ManyToManyField(related_name='assignment_groups', to='ndas.ndatemplate')),
                ('people', models.ManyToManyField(related_name='assignment_groups', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NDAAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=assignments.models._make_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('read', 'Read'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.TextField(blank=True, default='')),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ndas', to=settings.AUTH_USER_MODEL)),
                ('nda_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nda_assignments', to='ndas.ndatemplate')),
                ('nda_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nda_assignments', to='ndas.ndaversion')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nda_assignments', to='people.person')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='assignments.ndaassignmentgroup')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
