# Generated by Django 5.1.4 on 2026-02-19 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('employee', 'Employee'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('freelancer', 'Freelancer'), ('consultant', 'Consultant')], db_index=True, max_length=20)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_gst', models.CharField(blank=True, default='', max_length=30)),
                ('company_pan', models.CharField(blank=True, default='', max_length=20)),
                ('employee_id', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_exit', models.DateField(blank=True, null=True)),
                ('reporting_manager', models.CharField(blank=True, default='', max_length=255)),
                ('id_type', models.CharField(blank=True, default='', max_length=50)),
                ('id_number', models.CharField(blank=True, default='', max_length=100)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'person_type')},
            },
        ),
    ]
