# Generated by Django 5.1.4 on 2026-02-19 09:05

import django.db.models.deletion
import ndas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NDATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('employee', 'Employee'), ('client', 'Client / Customer'), ('partner', 'Partner'), ('consultant', 'Consultant'), ('freelancer', 'Freelancer'), ('vendor', 'Vendor'), ('additional', 'Additional')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('survival_years', models.IntegerField(default=5)),
                ('requires_witness', models.BooleanField(default=False)),
                ('auto_remind_days', models.IntegerField(default=3)),
                ('link_expiry_hours', models.IntegerField(default=72)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ndas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NDAVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20)),
                ('changelog', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('content_plain', models.TextField(blank=True, default='')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to=ndas.models.nda_file_path)),
                ('content_hash', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ndas.ndatemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='ndatemplate',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ndas.ndaversion'),
        ),
    ]
